/**
 * Master List of Popular US Stock Symbols & Company Names
 * Used for local autocomplete search to avoid API rate limits.
 * This covers the S&P 500, Nasdaq 100, and major ETFs.
 */

const STOCK_SYMBOLS = [
  { s: 'AAPL', n: 'Apple Inc.' },
  { s: 'MSFT', n: 'Microsoft Corporation' },
  { s: 'NVDA', n: 'NVIDIA Corporation' },
  { s: 'GOOGL', n: 'Alphabet Inc. (Class A)' },
  { s: 'GOOG', n: 'Alphabet Inc. (Class C)' },
  { s: 'AMZN', n: 'Amazon.com, Inc.' },
  { s: 'META', n: 'Meta Platforms, Inc.' },
  { s: 'TSLA', n: 'Tesla, Inc.' },
  { s: 'BRK.B', n: 'Berkshire Hathaway Inc.' },
  { s: 'AVGO', n: 'Broadcom Inc.' },
  { s: 'LLY', n: 'Eli Lilly and Company' },
  { s: 'JPM', n: 'JPMorgan Chase & Co.' },
  { s: 'UNH', n: 'UnitedHealth Group' },
  { s: 'V', n: 'Visa Inc.' },
  { s: 'XOM', n: 'Exxon Mobil Corporation' },
  { s: 'MA', n: 'Mastercard Incorporated' },
  { s: 'JNJ', n: 'Johnson & Johnson' },
  { s: 'PG', n: 'Procter & Gamble Company' },
  { s: 'HD', n: 'The Home Depot, Inc.' },
  { s: 'COST', n: 'Costco Wholesale Corporation' },
  { s: 'ABBV', n: 'AbbVie Inc.' },
  { s: 'MRK', n: 'Merck & Co., Inc.' },
  { s: 'AMD', n: 'Advanced Micro Devices, Inc.' },
  { s: 'ADBE', n: 'Adobe Inc.' },
  { s: 'CRM', n: 'Salesforce, Inc.' },
  { s: 'CVX', n: 'Chevron Corporation' },
  { s: 'NFLX', n: 'Netflix, Inc.' },
  { s: 'KO', n: 'The Coca-Cola Company' },
  { s: 'PEP', n: 'PepsiCo, Inc.' },
  { s: 'BAC', n: 'Bank of America Corporation' },
  { s: 'WMT', n: 'Walmart Inc.' },
  { s: 'ORCL', n: 'Oracle Corporation' },
  { s: 'TMO', n: 'Thermo Fisher Scientific' },
  { s: 'DIS', n: 'The Walt Disney Company' },
  { s: 'LIN', n: 'Linde plc' },
  { s: 'INTC', n: 'Intel Corporation' },
  { s: 'MCD', n: 'McDonald\'s Corporation' },
  { s: 'ABT', n: 'Abbott Laboratories' },
  { s: 'CSCO', n: 'Cisco Systems, Inc.' },
  { s: 'PFE', n: 'Pfizer Inc.' },
  { s: 'VZ', n: 'Verizon Communications' },
  { s: 'INTU', n: 'Intuit Inc.' },
  { s: 'CAT', n: 'Caterpillar Inc.' },
  { s: 'DHR', n: 'Danaher Corporation' },
  { s: 'IBM', n: 'International Business Machines' },
  { s: 'AMAT', n: 'Applied Materials, Inc.' },
  { s: 'ISRG', n: 'Intuitive Surgical, Inc.' },
  { s: 'QCOM', n: 'Qualcomm Incorporated' },
  { s: 'TXN', n: 'Texas Instruments' },
  { s: 'HON', n: 'Honeywell International Inc.' },
  { s: 'AXP', n: 'American Express Company' },
  { s: 'AMGN', n: 'Amgen Inc.' },
  { s: 'GE', n: 'General Electric Company' },
  { s: 'MS', n: 'Morgan Stanley' },
  { s: 'LOW', n: 'Lowe\'s Companies, Inc.' },
  { s: 'NEE', n: 'NextEra Energy, Inc.' },
  { s: 'PM', n: 'Philip Morris International' },
  { s: 'BKNG', n: 'Booking Holdings Inc.' },
  { s: 'UNP', n: 'Union Pacific Corporation' },
  { s: 'VRTX', n: 'Vertex Pharmaceuticals' },
  { s: 'SPY', n: 'SPDR S&P 500 ETF Trust' },
  { s: 'QQQ', n: 'Invesco QQQ Trust' },
  { s: 'PLTR', n: 'Palantir Technologies Inc.' },
  { s: 'SNOW', n: 'Snowflake Inc.' },
  { s: 'MSTR', n: 'MicroStrategy Incorporated' },
  { s: 'SHOP', n: 'Shopify Inc.' },
  { s: 'PYPL', n: 'PayPal Holdings, Inc.' },
  { s: 'Airbnb', n: 'Airbnb, Inc.' },
  { s: 'SQ', n: 'Block, Inc.' },
  { s: 'U', n: 'Unity Software Inc.' },
  { s: 'COIN', n: 'Coinbase Global, Inc.' },
  { s: 'GME', n: 'GameStop Corp.' },
  { s: 'AMC', n: 'AMC Entertainment Holdings' },
  { s: 'HOOD', n: 'Robinhood Markets, Inc.' },
  { s: 'ZM', n: 'Zoom Video Communications' },
  { s: 'RIVN', n: 'Rivian Automotive, Inc.' },
  { s: 'LCID', n: 'Lucid Group, Inc.' },
  // Exchange-Traded Funds (ETFs)
  { s: 'VOO', n: 'Vanguard S&P 500 ETF' },
  { s: 'VTI', n: 'Vanguard Total Stock Market ETF' },
  { s: 'IVV', n: 'iShares Core S&P 500 ETF' },
  { s: 'VUG', n: 'Vanguard Growth ETF' },
  { s: 'VEA', n: 'Vanguard FTSE Developed Markets ETF' },
  { s: 'VWO', n: 'Vanguard FTSE Emerging Markets ETF' },
  { s: 'IEFA', n: 'iShares Core MSCI EAFE ETF' },
  { s: 'AGG', n: 'iShares Core U.S. Aggregate Bond ETF' },
  { s: 'BND', n: 'Vanguard Total Bond Market ETF' },
  { s: 'ARKK', n: 'ARK Innovation ETF' },
  { s: 'SOXX', n: 'iShares Semiconductor ETF' },
  { s: 'SMH', n: 'VanEck Semiconductor ETF' },
  { s: 'SCHD', n: 'Schwab US Dividend Equity ETF' },
  { s: 'IWM', n: 'iShares Russell 2000 ETF' },
  { s: 'DIA', n: 'SPDR Dow Jones Industrial Average ETF Trust' }
];
